services:
  db-gps-server:
    image: mongo
    volumes:
      - mongo-data:/data/db
    # Allocate 50GB of RAM to the WiredTiger cache
    command: >
      mongod 
      --bind_ip 0.0.0.0 
      --port 27018 
      --wiredTigerCacheSizeGB 50
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hublic
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - my_custom_network
  gateway:
    build:
      context: .
      dockerfile: gateway-old/Dockerfile
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db-gps-server
    networks:
      - my_custom_network

  service-cp-realtime:
    build:
      context: .
      dockerfile: service-cp-realtime/Dockerfile
    depends_on:
      - db-gps-server
    networks:
      - my_custom_network

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - my_custom_network

networks:
  my_custom_network:
    external: true
    name: my_custom_network

volumes:
  mongo-data:
  portainer_data:
